name: Run pycopm in macOS

on:
 push:
   branches:
     - main
 pull_request:
   
jobs:
  run-pycopm-local:
    timeout-minutes: 120
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python 3.13
      uses: actions/setup-python@v2
      with:
        python-version: 3.13
    
    - name: Install OPM Flow dependencies
      run: |
        brew uninstall gcc cmake
        brew install boost openblas suite-sparse cmake open-mpi metis cjson zlib gfortran gcc fmt llvm@20

    - name: Build Third party dependecies (dune modules and Trilinos) and OPM Flow
      run: |
        CURRENT_DIRECTORY="$PWD"
        mkdir build
        mkdir build/ThirdParty

        git clone https://github.com/trilinos/Trilinos.git
        cd Trilinos && git checkout trilinos-release-17-0-0
        mkdir build && cd build
        cmake -DBUILD_SHARED_LIBS=ON -DTPL_ENABLE_MPI=ON -DTrilinos_ENABLE_ALL_PACKAGES=OFF -DTrilinos_ENABLE_Zoltan=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$CURRENT_DIRECTORY/build/ThirdParty" $CURRENT_DIRECTORY/Trilinos
        make -j5 && make install
        cd ../..

        for module in common geometry grid istl
        do  git clone https://gitlab.dune-project.org/core/dune-$module.git
            cd dune-$module && git checkout v2.11.0
            mkdir build && cd build
            cmake -DDUNE_ENABLE_PYTHONBINDINGS=0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$CURRENT_DIRECTORY/build/ThirdParty" $CURRENT_DIRECTORY/dune-$module
            make -j5 && make install
            cd ../..
        done
        for repo in common grid simulators
        do  git clone https://github.com/OPM/opm-$repo.git
            mkdir build/opm-$repo && cd build/opm-$repo
            cmake -DCMAKE_C_COMPILER=/opt/homebrew/opt/llvm@20/bin/clang -DCMAKE_CXX_COMPILER=/opt/homebrew/opt/llvm@20/bin/clang++ -DWITH_NDEBUG=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="$CURRENT_DIRECTORY/build/ThirdParty" $CURRENT_DIRECTORY/opm-$repo
            if [[ $repo == simulators ]]; then
              make -j5 flow
            else
              make -j5 opm$repo
            fi
            cd ../..
        done

    - name: Install pycopm in the Python virtual environment vpycopm
      run: |
        git clone https://github.com/cssr-tools/pycopm.git
        pushd pycopm
        python3 -m venv vpycopm
        source vpycopm/bin/activate
        pip install --upgrade pip setuptools wheel
        pip install .
        pip install -r dev-requirements.txt

    - name: Run the pycopm tests (explicitly passing the OPM Flow executable path)
      run: |
        pushd pycopm
        source vpycopm/bin/activate
        pytest --cov=pycopm --cov-report term-missing tests/ --flow /Users/runner/work/OPM-Flow_macOS/OPM-Flow_macOS/build/opm-simulators/bin/flow

    - name: Run the pycopm hello world example (globally exporting the OPM Flow executable path)
      run: |
        pushd pycopm
        source vpycopm/bin/activate
        export PATH=$PATH:/Users/runner/work/OPM-Flow_macOS/OPM-Flow_macOS/build/opm-simulators/bin
        pycopm -i examples/decks/HELLO_WORLD.DATA -c 5,5,1 -m all -f flow -o output

    - name: Check if the pycopm example succeded
      run: |
        file="/Users/runner/work/OPM-Flow_macOS/OPM-Flow_macOS/pycopm/output/HELLO_WORLD_PYCOPM.EGRID"
        if [[ -f "$file" ]]; then
          echo "pycopm succeeded"
        else
          echo "pycopm failed"
          exit 1
        fi
